src/main/java/org/itschool/hillel/model/ClassWork.java
package org.itschool.hillel.model;

import org.itschool.hillel.util.DateUtil;

import java.util.Date;

public class ClassWork {
    private Integer id;
    private Group group;
    private java.sql.Date date;
    private String theme;
    private String homeTask;

    public ClassWork() {
    }

    public ClassWork(Integer id, Group group, Date date, String theme, String homeTask) {
        this.id = id;
        this.group = group;
        this.date = new java.sql.Date(date.getTime());
        this.theme = theme;
        this.homeTask = homeTask;
    }

    public ClassWork(Integer id, Group group, java.sql.Date date, String theme, String homeTask) {
        this.id = id;
        this.group = group;
        this.date = date;
        this.theme = theme;
        this.homeTask = homeTask;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Group getGroup() {
        return group;
    }

    public void setGroup(Group group) {
        this.group = group;
    }

    public String getDateString() {
        return DateUtil.format.format(date);
    }

    public java.sql.Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = new java.sql.Date(date.getTime());
    }

    public String getTheme() {
        return theme;
    }

    public void setTheme(String theme) {
        this.theme = theme;
    }

    public String getHomeTask() {
        return homeTask;
    }

    public void setHomeTask(String homeTask) {
        this.homeTask = homeTask;
    }
}

src/main/java/org/itschool/hillel/controller/ClassWorkController.java
package org.itschool.hillel.controller;

import org.itschool.hillel.dao.ClassWorkDao;
import org.itschool.hillel.dao.ClassWorkDaoImpl;
import org.itschool.hillel.dao.GroupDao;
import org.itschool.hillel.dao.GroupDaoImpl;
import org.itschool.hillel.forms.ClassWorkForm;
import org.itschool.hillel.forms.FormUtil;
import org.itschool.hillel.model.ClassWork;
import org.itschool.hillel.model.Group;
import org.itschool.hillel.util.DateUtil;
import org.itschool.hillel.validation.Validator;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.text.ParseException;
import java.util.List;

@WebServlet("/class-works")
public class ClassWorkController extends HttpServlet {

    public GroupDao groupDao = GroupDaoImpl.getInstance();
    public ClassWorkDao classWorkDao = ClassWorkDaoImpl.getInstance();

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        showClassWorkListPage(req, resp, new ClassWorkForm());
    }

    @Override
    protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        ClassWorkForm form = FormUtil.readForm(req, ClassWorkForm.class);
        List<String> errors = Validator.validate(form);

        if (errors.size() > 0) {
            req.setAttribute("errors", errors);
            showClassWorkListPage(req, resp, form);
        } else {
            Group group = getGroup(req);
            ClassWork classWork = formToModel(form, group);
            classWorkDao.save(classWork);
            resp.sendRedirect("/class-works?groupId=" + group.getId());
        }
    }

    private void showClassWorkListPage(HttpServletRequest req, HttpServletResponse resp, ClassWorkForm form) throws ServletException, IOException {
        Group group = getGroup(req);
        List<ClassWork> classWorks = classWorkDao.list(group);

        req.setAttribute("group", group);
        req.setAttribute("classWorks", classWorks);
        req.setAttribute("form", form);

        req.getRequestDispatcher("WEB-INF/templates/class_works/list.jsp").forward(req, resp);
    }

    private Group getGroup(HttpServletRequest req) {
        int groupId = Integer.parseInt(req.getParameter("groupId"));
        return groupDao.get(groupId);
    }

    private ClassWork formToModel(ClassWorkForm form, Group group) {

        try {
            return new ClassWork(null,
                                 group,
                                 DateUtil.format.parse(form.getDate()),
                                 form.getTheme(),
                                 form.getHomeTask());
        } catch (ParseException e) {
            throw new RuntimeException(e);
        }
    }

}

src/main/webapp/WEB-INF/templates/class_works/_classWorkList.jsp
<h3>Class works</h3>

<p>
<table>
    <tr>
        <th>Date</th>
        <th>Theme</th>
        <th>Home task</th>
    </tr>
    <c:forEach items="${classWorks}" var="cw">
        <tr>
            <td>${cw.dateString}</td>
            <td>${cw.theme}</td>
            <td>${cw.homeTask}</td>
        </tr>
    </c:forEach>
</table>
</p>

src/main/webapp/WEB-INF/templates/class_works/_newClassWork.jsp
<h3>Create new student</h3>

<c:if test="${not empty errors}">
    <p>
            ${errors}
    </p>
</c:if>

<form method="post">
    <input type="hidden" name="groupId" value="${group.id}" />
    <div>
        <label for="date">Date</label>
        <input type="date" name="date" id="date" value="${form.date}"/>
    </div>
    <div>
        <label for="theme">Theme</label>
        <input type="text" name="theme" id="theme" value="${form.theme}"/>
    </div>
    <div>
        <label for="homeTask">Home task</label>
        <input type="text" name="homeTask" id="homeTask" value="${form.homeTask}"/>
    </div>
    <div>
        <button type="submit">Submit</button>
    </div>
</form>

src/main/webapp/WEB-INF/templates/class_works/list.jsp
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<c:set var="title" value="IT School" />
<jsp:include page="../shared/_header.jsp" />

Current User: ${currentUser}

<%@include file="_classWorkList.jsp" %>

<%@include file="_newClassWork.jsp" %>

<jsp:include page="../shared/_footer.jsp" />