src/main/java/org/itschool/hillel/model/Gender.java
package org.itschool.hillel.model;

public enum Gender {
    MALE {
        public String getAddressment() {
            return "Mr.";
        }
    },
    FEMALE {
        public String getAddressment() {
            return "Mrs.";
        }
    },
    UNKNOWN {
        public String getAddressment() {
            return "";
        }
    };

    public abstract String getAddressment();
}

src/main/java/org/itschool/hillel/model/Student.java
package org.itschool.hillel.model;

public class Student {

    private Integer id;
    private String firstName;
    private String secondName;
    private Gender gender;

    public Student() {
    }

    public Student(Integer id, String firstName, String secondName, Gender gender) {
        this.id = id;
        this.firstName = firstName;
        this.secondName = secondName;
        this.gender = gender;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getSecondName() {
        return secondName;
    }

    public void setSecondName(String secondName) {
        this.secondName = secondName;
    }

    public Gender getGender() {
        return gender;
    }

    public void setGender(Gender gender) {
        this.gender = gender;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Student student = (Student) o;

        if (!firstName.equals(student.firstName)) return false;
        if (!secondName.equals(student.secondName)) return false;

        return true;
    }

    @Override
    public int hashCode() {
        int result = firstName.hashCode();
        result = 31 * result + secondName.hashCode();
        return result;
    }

    @Override
    public String toString() {
        return "Student{" +
                "firstName='" + firstName + '\'' +
                ", secondName='" + secondName + '\'' +
                ", gender=" + gender +
                '}';
    }
}

src/main/java/org/itschool/hillel/controller/StudentsServlet.java
package org.itschool.hillel.controller;

import org.itschool.hillel.dao.GroupDao;
import org.itschool.hillel.dao.GroupDaoImpl;
import org.itschool.hillel.dao.StudentDao;
import org.itschool.hillel.dao.StudentDaoImpl;
import org.itschool.hillel.forms.StudentForm;
import org.itschool.hillel.model.Gender;
import org.itschool.hillel.model.Group;
import org.itschool.hillel.model.Student;
import org.itschool.hillel.validation.Validator;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.util.List;

@WebServlet("/students")
public class StudentsServlet extends HttpServlet {

    public StudentDao studentDao = StudentDaoImpl.getInstance();
    public GroupDao groupDao = GroupDaoImpl.getInstance();

    /**
     * Получение списка студентов для группы
     */
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        showStudentListPage(req, resp, new StudentForm());
    }

    @Override
    /**
     * Создание нового студента в группе
     */
    protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        StudentForm form = readStudent(req);
        List<String> errors = Validator.validate(form);

        if (errors.size() > 0) {
            req.setAttribute("errors", errors);
            showStudentListPage(req, resp, form);
        } else {
            Student student = formToStudent(form);
            Group group = getGroup(req);

            groupDao.addStudent(group, student);

            resp.sendRedirect("/students?groupId=" + group.getId());
        }
    }

    private void showStudentListPage(HttpServletRequest req, HttpServletResponse resp, StudentForm form) throws ServletException, IOException {
        Group group = getGroup(req);
        List<Student> students = studentDao.list(group);

        req.setAttribute("group", group);
        req.setAttribute("students", students);
        req.setAttribute("form", form);

        req.getRequestDispatcher("/WEB-INF/templates/students/list.jsp").forward(req, resp);
    }

    private StudentForm readStudent(HttpServletRequest req) {
        return new StudentForm(req.getParameter("firstname"),
                req.getParameter("secondname"),
                req.getParameter("age"),
                req.getParameter("gender"));
    }

    private Group getGroup(HttpServletRequest req) {
        int groupId = Integer.parseInt(req.getParameter("groupId"));
        return groupDao.get(groupId);
    }

    private Student formToStudent(StudentForm form) {
            Gender gender = form.getGender() == null
                    ? Gender.UNKNOWN
                    : Gender.valueOf(form.getGender().toUpperCase());

            return new Student(null, form.getFirstName(), form.getSecondName(), gender);
    }

}

src/main/webapp/WEB-INF/templates/students/_newStudent.jsp
<h3>Create new student</h3>

<c:if test="${not empty errors}">
    <p>
        ${errors}
    </p>
</c:if>

<form method="post">
    <input type="hidden" name="groupId" value="${group.id}" />
    <div>
        <label for="firstname">First name</label>
        <input type="text" name="firstname" id="firstname" value="${form.firstName}"/>
    </div>
    <div>
        <label for="secondname">Second name</label>
        <input type="text" name="secondname" id="secondname" value="${form.secondName}" />
    </div>
    <div>
        <label for="gender_male">Male</label>
        <input id="gender_male" type="radio" name="gender" value="MALE">

        <label for="gender_female">Female</label>
        <input id="gender_female" type="radio" name="gender" value="FEMALE">
    </div>
    <div>
        <button type="submit">Submit</button>
    </div>
</form>

src/main/webapp/WEB-INF/templates/students/_studentList.jsp
<h3>List of students</h3>

<p>
<ul>
  <c:forEach items="${students}" var="s">
    <li>${s.gender.addressment} ${s.firstName} ${s.secondName}</li>
  </c:forEach>
</ul>
</p>

src/main/webapp/WEB-INF/templates/students/list.jsp
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<c:set var="title" value="IT School" />
<jsp:include page="../shared/_header.jsp" />

Current User: ${currentUser}

<%@include file="_studentList.jsp" %>

<%@include file="_newStudent.jsp" %>

<jsp:include page="../shared/_footer.jsp" />